spring.application.name=FastFuriosFood1
spring.datasource.url=jdbc:mysql://localhost:3306/kge_osapi?createDatabaseIfNotExist=
spring.datasource.username=macdmj
spring.datasource.password=3diSenai
spring.jpa.show-sql=True