spring.application.name=FastFuriosFood1
spring.datasource.url=jdbc:mysql://172.16.0.30:3306/macdmj_fastFurious?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=macdmj
spring.datasource.password=2diSenai
spring.jpa.show-sql=True